### ISSUE TITLE
feat: Start publishing jars

### ISSUE THREAD

**Issue by jplaisted** [linkedin/datahub-gma#4]
We need to start publishing jars do DataHub can use them.

**Comment by jplaisted** [comment]
Before we start doing this, if we don't touch the code here are the jars we'll make today:

- ebean-dao
- elasticsearch-dao
- li-utils
- metadata-dao
- metadata-restli-resource
- metadata-test-models
- metadata-test-utils
- metadata-utils
- metadata-validators
- neo4j-dao

@mars-lan thoughts on this? I'd propose the following changes:

1. Drop the "metadata" prefix from packages.
2. Rename `li-utils` to `urn`
3. Delete `metadata-test-utils` entirely.
    a. Neo4j and ES shouldn't be used in the same module to avoid the dependency. If we _need_ these, they can move to their own modules.
    b. `TestUtils` doesn't do much and can easily be embedded.
    c. `AuditStamps`, while nice also isn't doing a ton. I don't think it justifies the existence of a "utils" module. We could move it to `test-models`. However, this file may be more widely used by DataHub and within LinkedIn. At the very least maybe we can just drop the "utils" from the module name; it it'd just be `testing`.
4. Move `metadata-utils` back into datahub. Code is used mostly by jobs and can move back when the "job libraries" move.

So after that we'd be left with:

- ebean-dao
- elasticsearch-dao
- urn
- dao
- restli-resource
- test-models
- testing
- validators
- neo4j-dao

**Comment by jplaisted** [comment]
Could also rename `metadata-dao` to `dao-api` instead.

**Comment by mars-lan** [comment]
Do we really want to rename everything? That means a lot of changes internally as well.

**Comment by jplaisted** [comment]
We already need internal changes when we switch from internal to external jars.

We don't have to rename anything, this is just a good time to do it if we want to :)

**Comment by mars-lan** [comment]
Agree. Some of these can use a better name :)

**Comment by jplaisted** [comment]
Any specific ideas or do I have carte blanche here? I'd rather discuss what we want upfront than in a PR.

**Comment by mars-lan** [comment]
1. `dao` sounds a bit too generic and confusing. Maybe rename it to `dao-api` or something?
2. Maybe rename `restli-resource` to `restli-resources` so it's consistent with the others?
3. `li-utils` contains more than just URN, unless you plan to move non-URN code/models out of the module?
4. Agree that `metadata-utils` should be moved back to datahub and maybe split into `factories` and `elasticsearch-support` or something.

**Comment by jplaisted** [comment]
Ok, sounds good, except 3. Maybe `base-models` or something instead of `urn`?

**Comment by mars-lan** [comment]
`base-models` can be misleading. Naming is the hardest thing in CS :)

**Comment by jplaisted** [comment]
`core-models`?

**Comment by mars-lan** [comment]
`core-models` SGTM
