### ISSUE TITLE
[search][filter] Do not use comma as a delimiter to specify multiple criteria

### ISSUE THREAD

**Issue by jywadhwani** [linkedin/datahub-gma#51]
#### Additional context
Some references to the code that splits the value provided in [`Criterion`](https://github.com/linkedin/datahub-gma/blob/master/dao-api/src/main/pegasus/com/linkedin/metadata/query/Criterion.pdl) model by commas include
https://github.com/linkedin/datahub-gma/blob/ca6b79cc5782b129d31fa8499916e4724f968830/dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/SearchUtils.java#L57
https://github.com/linkedin/datahub-gma/blob/ca6b79cc5782b129d31fa8499916e4724f968830/dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/utils/ESUtils.java#L66

**Comment by jplaisted** [comment]
I believe the above PR fixed this
